version: '3'
services:
    mavsdk_server:
        build: ./mavsdk_server
        ports:
            - "50051:50051"
            - "14540:14540/udp"
    gazebo_sitl_headless:
        image: jonasvautherin/px4-gazebo-headless:1.12.1
        environment:
            - NO_PXH=1
        links:
            - mavsdk_server
